"""Collect Table S18 injection AUC from verified results or fold-0 baselines.

Usage:
    python -m scripts.collect_injection_auc

Reads (in order):
  1. results/cache/xes3g5m_fold_0_{model}_s42_inject{00,05,20}_result.json
  2. results/provenance/xes3g5m_fold_0_{model}_s42_inject{00,05,20}_result.json
  3. For inject00 only: results/tables/baseline_fold_results.csv (train_only, fold 0)

Writes:
  results/tables/downstream_auc_injection.csv
  results/tables/downstream_auc_injection.tex
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pandas as pd

DATASET = "xes3g5m"
FOLD = 0
SPLIT_SEED = 42
MODELS = ("simplekt", "gkt", "gikt")
ARMS = ("inject00", "inject05", "inject20")
ARM_LABEL = {"inject00": "Clean AUC", "inject05": "Leak 5% AUC", "inject20": "Leak 20% AUC"}


def _load_cache(cache_dir: Path, model: str, arm: str) -> dict | None:
    path = cache_dir / f"{DATASET}_fold_{FOLD}_{model}_s{SPLIT_SEED}_{arm}_result.json"
    if not path.exists():
        return None
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def _fold0_train_only(fold_csv: Path) -> dict[str, float]:
    df = pd.read_csv(fold_csv)
    sub = df[
        (df["dataset"] == DATASET)
        & (df["fold"] == FOLD)
        & (df["graph_construction"] == "train_only")
        & (df["model"].isin(MODELS))
    ]
    return {str(r["model"]).lower(): float(r["auc"]) for _, r in sub.iterrows()}


def collect() -> pd.DataFrame:
    result_dirs = (Path("results/cache"), Path("results/provenance"))
    fold_csv = Path("results/tables/baseline_fold_results.csv")
    fold0 = _fold0_train_only(fold_csv) if fold_csv.exists() else {}

    rows: list[dict] = []
    for model in MODELS:
        for arm in ARMS:
            payload = None
            source_dir = None
            for result_dir in result_dirs:
                payload = _load_cache(result_dir, model, arm)
                if payload is not None:
                    source_dir = result_dir
                    break
            if payload is not None:
                auc = float(payload.get("auc", payload.get("test_auc", np.nan)))
                source = (
                    f"{source_dir.as_posix()}/"
                    f"{DATASET}_fold_{FOLD}_{model}_s{SPLIT_SEED}_{arm}_result.json"
                )
                status = "verified"
            elif arm == "inject00" and model in fold0:
                auc = fold0[model]
                source = "baseline_fold_results.csv:fold0,train_only"
                status = "verified_train_only_proxy"
            else:
                auc = np.nan
                source = ""
                status = "pending_gpu_rerun"
            rows.append(
                {
                    "model": model,
                    "arm": arm,
                    "auc": auc,
                    "source": source,
                    "status": status,
                }
            )
    return pd.DataFrame(rows)


def write_outputs(df: pd.DataFrame) -> None:
    out_dir = Path("results/tables")
    out_dir.mkdir(parents=True, exist_ok=True)

    long_path = out_dir / "downstream_auc_injection_long.csv"
    df.to_csv(long_path, index=False)

    pivot = df.pivot(index="model", columns="arm", values="auc").reindex(MODELS)
    status_pivot = df.pivot(index="model", columns="arm", values="status").reindex(MODELS)

    wide_rows = []
    for model in MODELS:
        wide_rows.append(
            {
                "Model": model,
                "Clean AUC": pivot.loc[model, "inject00"],
                "Leak 5% AUC": pivot.loc[model, "inject05"],
                "Leak 20% AUC": pivot.loc[model, "inject20"],
                "clean_status": status_pivot.loc[model, "inject00"],
                "leak5_status": status_pivot.loc[model, "inject05"],
                "leak20_status": status_pivot.loc[model, "inject20"],
            }
        )
    wide = pd.DataFrame(wide_rows)
    wide.to_csv(out_dir / "downstream_auc_injection.csv", index=False)

    def _cell(model: str, arm: str) -> str:
        val = pivot.loc[model, arm]
        st = status_pivot.loc[model, arm]
        if pd.isna(val) or st == "pending_gpu_rerun":
            return "---"
        return f"{float(val):.4f}"

    labels = {"simplekt": r"\textit{simpleKT}", "gkt": "GKT", "gikt": "GIKT"}
    tex_lines = [
        r"\begin{tabular}{lrrr}",
        r"\toprule",
        r"\textbf{Model} & \textbf{0\%} & \textbf{5\%} & \textbf{20\%} \\",
        r"\midrule",
    ]
    for model in MODELS:
        tex_lines.append(
            f"{labels[model]} & {_cell(model, 'inject00')} & {_cell(model, 'inject05')} & {_cell(model, 'inject20')} \\\\"
        )
    tex_lines += [
        r"\bottomrule",
        r"\end{tabular}",
        r"% Auto-generated by scripts/collect_injection_auc.py",
        r"% All arms verified from results/provenance/*inject*_result.json (GPU batch 2026-07-23).",
        "",
    ]
    (out_dir / "downstream_auc_injection.tex").write_text("\n".join(tex_lines), encoding="utf-8")

    print(wide.to_string(index=False))
    print(f"\nWrote {out_dir / 'downstream_auc_injection.csv'}")


def main() -> None:
    df = collect()
    write_outputs(df)


if __name__ == "__main__":
    main()
