#!/usr/bin/env python3
"""Compute sequence-autocorrelation diagnostics for KT benchmarks.

For each dataset we order interactions per learner by timestamp and measure how
predictable each step is from the immediately preceding one. The statistics
quantify the ``copy-the-previous-answer'' shortcut that inflates deep-KT AUC on
repetition-heavy logs (Section: Sequence Autocorrelation Analysis).

Outputs
-------
- results/tables/autocorrelation_stats.csv
- results/tables/autocorrelation_stats.tex
"""

from __future__ import annotations

import argparse
import logging
import sys
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.metrics import roc_auc_score

ROOT = Path(__file__).resolve().parents[1]
logger = logging.getLogger(__name__)

DATASETS = {
    "Junyi Academy": "data/processed/junyi.parquet",
    "ASSISTments 2012": "data/processed/assist2012.parquet",
    "XES3G5M": "data/processed/xes3g5m.parquet",
}


def _consecutive_stats(df: pd.DataFrame) -> dict:
    """Vectorised consecutive-pair statistics within learner sequences."""
    df = df.sort_values(["user_id", "timestamp"], kind="stable").reset_index(drop=True)
    user = df["user_id"].to_numpy()
    # A pair (t-1, t) is valid only when both rows belong to the same learner.
    same_user = user[1:] == user[:-1]

    kc = df["kc_id"].to_numpy()
    item = df["item_id"].to_numpy()
    y = df["correct"].to_numpy().astype(np.int8)

    kc_rep = (kc[1:] == kc[:-1]) & same_user
    item_rep = (item[1:] == item[:-1]) & same_user

    y_prev = y[:-1][same_user]
    y_cur = y[1:][same_user]
    n_pairs = int(same_user.sum())

    persistence_acc = float((y_cur == y_prev).mean()) if n_pairs else float("nan")
    # Lag-1 label autocorrelation (Pearson).
    if n_pairs and y_cur.std() > 0 and y_prev.std() > 0:
        lag1_corr = float(np.corrcoef(y_cur, y_prev)[0, 1])
    else:
        lag1_corr = float("nan")
    # AUC of the trivial "previous answer" predictor.
    if n_pairs and len(np.unique(y_cur)) == 2:
        prev_answer_auc = float(roc_auc_score(y_cur, y_prev))
    else:
        prev_answer_auc = float("nan")

    return {
        "n_interactions": int(len(df)),
        "n_users": int(df["user_id"].nunique()),
        "n_pairs": n_pairs,
        "kc_repeat_rate": float(kc_rep.sum() / n_pairs) if n_pairs else float("nan"),
        "item_repeat_rate": float(item_rep.sum() / n_pairs) if n_pairs else float("nan"),
        "label_persistence_acc": persistence_acc,
        "lag1_label_corr": lag1_corr,
        "prev_answer_auc": prev_answer_auc,
    }


def _write_tex(df: pd.DataFrame, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    rows = []
    for _, r in df.iterrows():
        rows.append(
            f"{r['dataset']} & {r['kc_repeat_rate']:.3f} & {r['item_repeat_rate']:.3f} & "
            f"{r['label_persistence_acc']:.3f} & {r['lag1_label_corr']:.3f} & "
            f"{r['prev_answer_auc']:.3f} \\\\"
        )
    body = "\n".join(rows)
    tex = (
        "% Auto-generated by scripts/compute_autocorrelation.py\n"
        "\\begin{table}[t]\n\\centering\n"
        "\\caption{Sequence-autocorrelation diagnostics on the three public benchmarks. "
        "\\emph{KC rep.} and \\emph{Item rep.} are the fractions of consecutive within-learner "
        "interactions that repeat the previous KC or item; \\emph{Persist.\\ acc.} is "
        "$P(y_t{=}y_{t-1})$; \\emph{Lag-1 $\\rho$} is the lag-one label autocorrelation; "
        "\\emph{Prev-AUC} is the AUC of the trivial predictor $\\hat y_t{=}y_{t-1}$.}\n"
        "\\label{tab:autocorrelation}\n"
        "\\footnotesize\n\\setlength{\\tabcolsep}{3pt}\n"
        "\\begin{tabularx}{\\linewidth}{@{} >{\\RaggedRight\\arraybackslash}X *{5}{>{\\centering\\arraybackslash}X} @{}}\n"
        "\\toprule\n"
        "Dataset & KC rep. & Item rep. & Persist. acc. & Lag-1 $\\rho$ & Prev-AUC \\\\\n"
        "\\midrule\n"
        f"{body}\n"
        "\\bottomrule\n\\end{tabularx}\n\\end{table}\n"
    )
    path.write_text(tex, encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out-csv", default="results/tables/autocorrelation_stats.csv")
    parser.add_argument("--out-tex", default="results/tables/autocorrelation_stats.tex")
    args = parser.parse_args()

    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")

    records = []
    for label, rel_path in DATASETS.items():
        path = ROOT / rel_path
        if not path.exists():
            logger.warning("Skipping %s: %s not found", label, path)
            continue
        logger.info("Loading %s ...", label)
        df = pd.read_parquet(path, columns=["user_id", "item_id", "kc_id", "timestamp", "correct"])
        stats = _consecutive_stats(df)
        stats["dataset"] = label
        records.append(stats)
        logger.info(
            "%s: kc_rep=%.3f item_rep=%.3f persist=%.3f lag1=%.3f prevAUC=%.3f",
            label, stats["kc_repeat_rate"], stats["item_repeat_rate"],
            stats["label_persistence_acc"], stats["lag1_label_corr"], stats["prev_answer_auc"],
        )

    if not records:
        logger.error("No datasets processed.")
        return 1

    cols = [
        "dataset", "n_interactions", "n_users", "n_pairs",
        "kc_repeat_rate", "item_repeat_rate", "label_persistence_acc",
        "lag1_label_corr", "prev_answer_auc",
    ]
    out = pd.DataFrame.from_records(records)[cols]
    out_csv = ROOT / args.out_csv
    out_csv.parent.mkdir(parents=True, exist_ok=True)
    out.to_csv(out_csv, index=False)
    _write_tex(out, ROOT / args.out_tex)
    logger.info("Wrote %s and %s", out_csv, ROOT / args.out_tex)
    print(out.to_string(index=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
