"""Cross-check headline AUC numbers across tables and verified provenance JSON.

Usage:
    python -m scripts.crossref_auc_numbers

Writes: audit/crossref_auc_report.md
"""

from __future__ import annotations

import json
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "audit" / "crossref_auc_report.md"
TOL = 0.002


def _load_json(path: Path) -> float | None:
    if not path.exists():
        return None
    data = json.loads(path.read_text(encoding="utf-8"))
    return float(data.get("auc", data.get("test_auc", float("nan"))))


def main() -> None:
    rows: list[dict] = []
    fold = pd.read_csv(ROOT / "results/tables/baseline_fold_results.csv")
    summary = pd.read_csv(ROOT / "results/tables/baseline_results.csv")
    inject = pd.read_csv(ROOT / "results/tables/downstream_auc_injection.csv")
    provenance = ROOT / "results/provenance"

    trio = ("simplekt", "gkt", "gikt")
    for model in trio:
        fsub = fold[
            (fold["dataset"] == "xes3g5m")
            & (fold["model"] == model)
            & (fold["graph_construction"] == "train_only")
        ]
        mean_fold = float(fsub["auc"].mean()) if not fsub.empty else float("nan")
        ssub = summary[
            (summary["dataset"] == "xes3g5m")
            & (summary["model"] == model)
            & (summary["graph_construction"] == "train_only")
        ]
        mean_summary = float(ssub["auc"].iloc[0]) if not ssub.empty else float("nan")
        fold0 = float(fsub[fsub["fold"] == 0]["auc"].iloc[0]) if not fsub[fsub["fold"] == 0].empty else float("nan")
        inj_row = inject[inject["Model"] == model]
        clean_inject = float(inj_row["Clean AUC"].iloc[0]) if not inj_row.empty else float("nan")
        cache00 = _load_json(provenance / f"xes3g5m_fold_0_{model}_s42_inject00_result.json")
        ok_summary = abs(mean_fold - mean_summary) <= TOL if pd.notna(mean_fold) and pd.notna(mean_summary) else False
        ok_inject = abs(fold0 - clean_inject) <= TOL if pd.notna(fold0) and pd.notna(clean_inject) else False
        rows.append(
            {
                "check": f"xes3g5m/{model}/train_only",
                "fold_mean": mean_fold,
                "baseline_results": mean_summary,
                "fold0": fold0,
                "S18_clean": clean_inject,
                "inject00_cache": cache00,
                "summary_ok": ok_summary,
                "inject_clean_ok": ok_inject,
            }
        )

    for model in trio:
        inj_row = inject[inject["Model"] == model]
        if inj_row.empty:
            continue
        for col, arm in [("Leak 5% AUC", "inject05"), ("Leak 20% AUC", "inject20")]:
            val = inj_row[col].iloc[0]
            if pd.isna(val):
                rows.append({"check": f"S18/{model}/{arm}", "status": "MISSING"})
                continue
            cached = _load_json(provenance / f"xes3g5m_fold_0_{model}_s42_{arm}_result.json")
            ok = cached is not None and abs(float(val) - cached) <= 1e-9
            rows.append(
                {
                    "check": f"S18/{model}/{arm}",
                    "table": float(val),
                    "cache": cached,
                    "ok": ok,
                }
            )

    lines = [
        "# Cross-reference AUC report",
        "",
        f"Generated by `scripts/crossref_auc_numbers.py` (tolerance {TOL} for fold vs summary).",
        "",
        "## Primary XES3G5M trio (train_only)",
        "",
        "| Check | fold mean | baseline_results | fold0 | S18 clean | inject00 provenance | summary OK | clean OK |",
        "|---|---:|---:|---:|---:|---:|---|---|",
    ]
    for r in rows:
        if "fold_mean" not in r:
            continue
        lines.append(
            f"| {r['check']} | {r['fold_mean']:.4f} | {r['baseline_results']:.4f} | "
            f"{r['fold0']:.4f} | {r['S18_clean']:.4f} | "
            f"{r['inject00_cache'] if r['inject00_cache'] is not None else '—'} | "
            f"{'✓' if r['summary_ok'] else '✗'} | {'✓' if r['inject_clean_ok'] else '✗'} |"
        )

    lines += [
        "",
        "## S18 leak arms vs provenance",
        "",
        "| Check | table | provenance | OK |",
        "|---|---:|---:|---|",
    ]
    for r in rows:
        if "fold_mean" in r:
            continue
        if r.get("status") == "MISSING":
            lines.append(f"| {r['check']} | — | — | ✗ |")
        else:
            lines.append(
                f"| {r['check']} | {r['table']:.6f} | {r['cache']:.6f} | {'✓' if r['ok'] else '✗'} |"
            )

    fails = [r for r in rows if r.get("summary_ok") is False or r.get("inject_clean_ok") is False or r.get("ok") is False or r.get("status") == "MISSING"]
    lines += ["", f"**Failures:** {len(fails)}", ""]
    OUT.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"Wrote {OUT}")
    if fails:
        print(f"WARNING: {len(fails)} check(s) failed")
        raise SystemExit(1)
    print("All checks passed")


if __name__ == "__main__":
    main()
