"""OLS slope of AUC-drop on DDR with fold-clustered bootstrap CIs (T2/T4).

Usage:
    python scripts/ddr_slope_ci.py
    python scripts/ddr_slope_ci.py --sync-tex
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np
import pandas as pd
from scipy import stats

ROOT = Path(__file__).resolve().parents[1]
CORE_OPS = ("edge_drop", "node_drop", "prereq_preserve")


def ols_intercept_slope(x: np.ndarray, y: np.ndarray) -> tuple[float, float]:
    x = np.asarray(x, dtype=float)
    y = np.asarray(y, dtype=float)
    ok = np.isfinite(x) & np.isfinite(y)
    x, y = x[ok], y[ok]
    if x.size < 3:
        return float("nan"), float("nan")
    xc = x - x.mean()
    denom = float(np.dot(xc, xc))
    if denom <= 0:
        return float("nan"), float("nan")
    slope = float(np.dot(xc, y - y.mean()) / denom)
    intercept = float(y.mean() - slope * x.mean())
    return intercept, slope


def cluster_bootstrap_slope(
    frame: pd.DataFrame,
    *,
    x_col: str = "ddr",
    y_col: str = "auc_drop",
    cluster_col: str = "cluster",
    n_boot: int = 2000,
    seed: int = 42,
) -> tuple[float, float, float]:
    """Percentile CI for OLS slope; clusters resampled with replacement."""
    grouped = {key: part for key, part in frame.groupby(cluster_col, sort=False)}
    keys = list(grouped)
    if len(keys) < 2:
        _, slope = ols_intercept_slope(frame[x_col].to_numpy(), frame[y_col].to_numpy())
        return slope, float("nan"), float("nan")
    rng = np.random.default_rng(seed)
    slopes = np.empty(n_boot, dtype=float)
    for i in range(n_boot):
        draw = rng.choice(keys, size=len(keys), replace=True)
        boot = pd.concat([grouped[k] for k in draw], ignore_index=True)
        _a, slopes[i] = ols_intercept_slope(boot[x_col].to_numpy(), boot[y_col].to_numpy())
    _, point = ols_intercept_slope(frame[x_col].to_numpy(), frame[y_col].to_numpy())
    lo, hi = np.quantile(slopes[np.isfinite(slopes)], [0.025, 0.975])
    return float(point), float(lo), float(hi)


def _cluster_id(df: pd.DataFrame) -> pd.Series:
    seed = df["split_seed"] if "split_seed" in df.columns else 0
    return df["dataset"].astype(str) + "|" + df["fold"].astype(str) + "|" + pd.Series(seed, index=df.index).astype(str)


def subset(
    df: pd.DataFrame,
    *,
    dataset: str,
    model: str,
    p_max: float | None,
) -> pd.DataFrame:
    part = df[(df["dataset"] == dataset) & (df["model"] == model)].copy()
    part = part[part["operator"].isin(CORE_OPS)]
    part = part[pd.notna(part["ddr"]) & pd.notna(part["auc_drop"])]
    if p_max is not None:
        part = part[part["p"].astype(float) <= p_max + 1e-9]
    part["cluster"] = _cluster_id(part)
    return part.reset_index(drop=True)


def estimand_row(
    df: pd.DataFrame, dataset: str, model: str, scope: str, p_max: float | None, n_boot: int = 2000
) -> dict:
    part = subset(df, dataset=dataset, model=model, p_max=p_max)
    x = part["ddr"].to_numpy()
    y = part["auc_drop"].to_numpy()
    intercept, slope = ols_intercept_slope(x, y)
    slope_hat, lo, hi = cluster_bootstrap_slope(part, n_boot=n_boot)
    n = int(len(part))
    n_clusters = int(part["cluster"].nunique())
    r = float(stats.pearsonr(x, y)[0]) if n >= 3 else float("nan")
    rho = float(stats.spearmanr(x, y)[0]) if n >= 3 else float("nan")
    return {
        "dataset": dataset,
        "model": model,
        "scope": scope,
        "n": n,
        "n_clusters": n_clusters,
        "pearson_r": r,
        "spearman_rho": rho,
        "intercept": intercept,
        "slope": slope_hat,
        "slope_ci_lo": lo,
        "slope_ci_hi": hi,
    }


def _fmt_ci(lo: float, hi: float, digits: int = 3) -> str:
    return rf"$[{lo:+.{digits}f}, {hi:+.{digits}f}]$"


def write_macros(rows: list[dict], path: Path) -> None:
    by = {(r["dataset"], r["model"], r["scope"]): r for r in rows}
    xes_core = by[("xes3g5m", "gkt", "core")]
    xes_full = by[("xes3g5m", "gkt", "core+anchors")]
    ast_core = by[("assist2012", "gkt", "core")]
    ast_full = by[("assist2012", "gkt", "core+anchors")]
    lines = [
        r"% Auto-generated by scripts/ddr_slope_ci.py — do not edit.",
        rf"\newcommand{{\DDRslopeXEScore}}{{{xes_core['slope']:.3f}}}",
        rf"\newcommand{{\DDRslopeXEScoreci}}{{{_fmt_ci(xes_core['slope_ci_lo'], xes_core['slope_ci_hi'], 3)}}}",
        rf"\newcommand{{\DDRslopeXESfull}}{{{xes_full['slope']:.3f}}}",
        rf"\newcommand{{\DDRslopeXESfullci}}{{{_fmt_ci(xes_full['slope_ci_lo'], xes_full['slope_ci_hi'], 3)}}}",
        rf"\newcommand{{\DDRslopeASSISTcore}}{{{ast_core['slope']:.4f}}}",
        rf"\newcommand{{\DDRslopeASSISTcoreci}}{{{_fmt_ci(ast_core['slope_ci_lo'], ast_core['slope_ci_hi'], 4)}}}",
        rf"\newcommand{{\DDRslopeASSISTfull}}{{{ast_full['slope']:.4f}}}",
        rf"\newcommand{{\DDRslopeASSISTfullci}}{{{_fmt_ci(ast_full['slope_ci_lo'], ast_full['slope_ci_hi'], 4)}}}",
        rf"\newcommand{{\DDRnXEScore}}{{{int(xes_core['n'])}}}",
        rf"\newcommand{{\DDRnXESfull}}{{{int(xes_full['n'])}}}",
        "",
    ]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--in-csv", type=Path, default=ROOT / "results" / "tables" / "ddr_downstream.csv")
    parser.add_argument("--out-csv", type=Path, default=ROOT / "results" / "tables" / "ddr_slope_ci.csv")
    parser.add_argument("--out-macros", type=Path, default=ROOT / "results" / "tables" / "ddr_slope_macros.tex")
    parser.add_argument("--n-boot", type=int, default=2000)
    parser.add_argument("--sync-tex", action="store_true")
    args = parser.parse_args()

    df = pd.read_csv(args.in_csv)
    df["p"] = df["p"].astype(float)
    specs = [
        ("xes3g5m", "gkt", "core", 0.3),
        ("xes3g5m", "gkt", "core+anchors", None),
        ("assist2012", "gkt", "core", 0.3),
        ("assist2012", "gkt", "core+anchors", None),
        ("xes3g5m", "dgekt", "core", 0.3),
        ("assist2012", "dgekt", "core", 0.3),
    ]
    rows = [estimand_row(df, ds, model, scope, p_max, n_boot=args.n_boot) for ds, model, scope, p_max in specs]
    out = pd.DataFrame(rows)
    args.out_csv.parent.mkdir(parents=True, exist_ok=True)
    out.to_csv(args.out_csv, index=False)
    write_macros(rows, args.out_macros)
    print(out.to_string(index=False, float_format=lambda v: f"{v: .4f}"))
    print(f"Wrote {args.out_csv}")
    print(f"Wrote {args.out_macros}")
    if args.sync_tex:
        dest = ROOT / "paper" / "submission_EAAI" / "ddr_slope_macros.tex"
        dest.write_text(args.out_macros.read_text(encoding="utf-8"), encoding="utf-8")
        print(f"Synced {dest}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
