"""Emit Table S15 training_parity.tex from configs/xes3g5m.yaml."""

from __future__ import annotations

from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]

DISPLAY = {
    "bkt": "BKT",
    "dkt": "DKT",
    "simplekt": r"\textit{simpleKT}",
    "akt": "AKT",
    "gkt": "GKT",
    "gikt": "GIKT",
    "skt": "SKT",
    "dygkt": "DyGKT",
    "dgekt": "DGEKT",
}

MODEL_ROWS = [
    ("bkt", "scipy", r"\texttt{scipy} L-BFGS", "---", "scipy_lbfgs"),
    ("dkt", "pykt", r"\texttt{pyKT} stock", "---", "pykt_stock"),
    ("simplekt", "pykt", r"\texttt{pyKT} stock", "---", "pykt_stock"),
    ("akt", "pykt", r"\texttt{pyKT} stock", "---", "pykt_stock"),
    ("gkt", "pykt", r"\texttt{pyKT} stock", r"$\Epre + \Esim$", "pykt_stock"),
    ("gikt", "native", "native", r"$\Epre + \Esim$", "native"),
    ("skt", "native", "native", r"$\Epre + \Esim$", "native"),
    ("dygkt", "native", "native", r"$\Epre + \Esim$", "native"),
    ("dgekt", "native", "native", r"$\Epre + \Esim$", "native"),
]


def _hp(cfg: dict, name: str) -> tuple[int, int]:
    pykt = cfg.get("pykt", {})
    baseline = next((b for b in cfg.get("baselines", []) if b.get("name") == name), {})
    hp = baseline.get("hyperparams", {})
    epochs = int(hp.get("epochs", pykt.get("epochs", 30)))
    batch = int(hp.get("batch_size", pykt.get("batch_size", 64)))
    return epochs, batch


def main() -> None:
    cfg_path = ROOT / "configs/xes3g5m.yaml"
    cfg = yaml.safe_load(cfg_path.read_text(encoding="utf-8"))

    lines = [
        r"% Auto-generated by scripts/generate_training_parity.py",
        r"\begin{tabular}{llcrrcll}",
        r"\toprule",
        r"\textbf{Model} & \textbf{Codebase} & \textbf{Graph input} & \textbf{Epochs} & \textbf{Batch} & \textbf{ES patience} & \textbf{Runtime} & \textbf{Hardware} \\",
        r"\midrule",
    ]
    for name, kind, codebase, graph, key in MODEL_ROWS:
        if key == "scipy_lbfgs":
            epochs, batch, patience = 30, 64, "N/A"
        else:
            epochs, batch = _hp(cfg, name)
            patience = 5
        display = DISPLAY[name]
        runtime = r"$<$5\,min" if name == "bkt" else r"30--180\,min"
        hw = "CPU" if name == "bkt" else "A100/V100"
        lines.append(
            f"{display} & {codebase} & {graph} & {epochs} & {batch} & {patience} & {runtime} & {hw} \\\\"
        )
    ablation_cfg = yaml.safe_load((ROOT / "configs/xes3g5m_gkt_epochs30.yaml").read_text(encoding="utf-8"))
    ablation_pykt = ablation_cfg.get("pykt", {})
    ablation_epochs = int(ablation_pykt.get("epochs", 30))
    ablation_batch = int(ablation_pykt.get("batch_size", 32))
    lines += [
        r"\bottomrule",
        r"\end{tabular}",
        r"\par\smallskip",
        rf"\footnotesize Epoch-matched GKT ablation (Tables~S21--S22): "
        rf"\texttt{{configs/xes3g5m\_gkt\_epochs30.yaml}} ({ablation_epochs} epochs, batch {ablation_batch}; "
        r"\textit{simpleKT} reference runs in S22 retain batch~64 from Phase-3 trio reruns).",
        "",
    ]
    out = ROOT / "results/tables/training_parity.tex"
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {out}")


if __name__ == "__main__":
    main()
