"""Emit Table S15 training_parity.tex from canonical_training_protocol.yaml.

Does not invent epoch/batch from HEAD configs alone. Primary GKT/simpleKT
come from the attested protocol; other models keep config-file HPs with an
explicit footnote that GKT/simpleKT rows are protocol-attested.
"""

from __future__ import annotations

from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
PROTOCOL = ROOT / "audit" / "2026-07-17-1541" / "canonical_training_protocol.yaml"

DISPLAY = {
    "bkt": "BKT",
    "dkt": "DKT",
    "simplekt": r"\textit{simpleKT}",
    "akt": "AKT",
    "gkt": "GKT",
    "gikt": "GIKT",
    "skt": "SKT",
    "dygkt": "DyGKT",
    "dgekt": "DGEKT",
}

MODEL_ROWS = [
    ("bkt", "scipy", r"\texttt{scipy} L-BFGS", "---", "scipy_lbfgs"),
    ("dkt", "pykt", r"\texttt{pyKT} stock", "---", "pykt_stock"),
    ("simplekt", "pykt", r"\texttt{pyKT} stock", "---", "pykt_stock"),
    ("akt", "pykt", r"\texttt{pyKT} stock", "---", "pykt_stock"),
    ("gkt", "pykt", r"\texttt{pyKT} stock", r"$\Epre + \Esim$", "pykt_stock"),
    ("gikt", "native", "native", r"$\Epre + \Esim$", "native"),
    ("skt", "native", "native", r"$\Epre + \Esim$", "native"),
    ("dygkt", "native", "native", r"$\Epre + \Esim$", "native"),
    ("dgekt", "native", "native", r"$\Epre + \Esim$", "native"),
]


def _hp(cfg: dict, name: str) -> tuple[int, int]:
    pykt = cfg.get("pykt", {})
    baseline = next((b for b in cfg.get("baselines", []) if b.get("name") == name), {})
    hp = baseline.get("hyperparams", {})
    epochs = int(hp.get("epochs", pykt.get("epochs", 30)))
    batch = int(hp.get("batch_size", pykt.get("batch_size", 64)))
    return epochs, batch


def main() -> None:
    if not PROTOCOL.exists():
        raise FileNotFoundError(f"Missing canonical protocol: {PROTOCOL}")
    proto = yaml.safe_load(PROTOCOL.read_text(encoding="utf-8"))
    gkt_ep = int(proto["primary"]["gkt"]["max_epochs"])
    gkt_bs = int(proto["primary"]["gkt"]["batch_size"])
    skt_ep = int(proto["primary"]["simplekt"]["max_epochs"])
    skt_bs = int(proto["primary"]["simplekt"]["batch_size"])
    if (gkt_ep, gkt_bs) != (10, 4) or (skt_ep, skt_bs) != (30, 64):
        raise ValueError("Canonical primary protocol mismatch for S15")

    cfg = yaml.safe_load((ROOT / "configs/xes3g5m.yaml").read_text(encoding="utf-8"))
    tgt = proto["targeted_extended_training"]
    ext_ep = int(tgt["gkt_extended"]["max_epochs"])
    ext_bs = int(tgt["gkt_extended"]["batch_size"])

    lines = [
        r"% Auto-generated by scripts/generate_training_parity.py",
        r"% Primary GKT/simpleKT rows: canonical_training_protocol.yaml (author-attested).",
        r"% Column ``Max epochs'' = configured maximum epoch budget (not necessarily executed epochs).",
        r"% J04: tabularx + short headers (do not use \\resizebox inside table floats).",
        r"\footnotesize",
        r"\setlength{\tabcolsep}{2.5pt}",
        r"\begin{tabularx}{\textwidth}{@{}l l >{\Centering\arraybackslash}X c c c c c@{}}",
        r"\toprule",
        r"\textbf{Model} & \textbf{Codebase} & \textbf{Graph} & \textbf{Epochs} & "
        r"\textbf{Batch} & \textbf{ES} & \textbf{Runtime} & \textbf{HW} \\",
        r"\midrule",
    ]
    for name, kind, codebase, graph, key in MODEL_ROWS:
        if key == "scipy_lbfgs":
            epochs, batch, patience = 30, 64, "N/A"
        elif name == "gkt":
            epochs, batch, patience = gkt_ep, gkt_bs, 5
        elif name == "simplekt":
            epochs, batch, patience = skt_ep, skt_bs, 5
        else:
            epochs, batch = _hp(cfg, name)
            patience = 5
        display = DISPLAY[name]
        if name == "bkt":
            runtime, hw = r"$<$0.1\,h", "CPU"
        elif name == "gkt":
            # ~20 min/epoch on RTX 3090 → ~2--4 h at the 10-epoch cap (hours throughout).
            runtime, hw = r"$\sim$2--4\,h", r"RTX\,3090"
        else:
            runtime, hw = r"$\sim$0.5--3\,h", r"RTX\,3090"
        graph_cell = "---" if graph == "---" else r"$\Epre{+}\Esim$"
        lines.append(
            f"{display} & {codebase} & {graph_cell} & {epochs} & {batch} & {patience} & {runtime} & {hw} \\\\"
        )
    lines += [
        r"\bottomrule",
        r"\end{tabularx}",
        r"\par\smallskip",
        r"\footnotesize Primary GKT/\textit{simpleKT} budgets are author-attested "
        r"(commit \texttt{619c02cf}): "
        rf"GKT max.\ {gkt_ep} epochs, batch {gkt_bs}; "
        rf"\textit{{simpleKT}} max.\ {skt_ep} epochs, batch {skt_bs}. "
        r"HW~=~RTX\,3090 denotes one NVIDIA GeForce RTX\,3090 (24\,GB); not A100/V100. "
        r"Runtime is approximate wall-clock on that GPU (CPU for BKT), reported in hours. "
        r"GKT $\sim$2--4\,h corresponds to an observed $\sim$0.33\,h/epoch ($\sim$20\,min/epoch) "
        r"on XES3G5M-scale folds at the 10-epoch cap with early stopping; "
        r"other GPU rows are coarse order-of-magnitude estimates. "
        rf"Table~S21: exploratory seed-42 three-fold GKT check "
        rf"(max.\ {ext_ep} epochs, batch {ext_bs}); not compute-matched / not epoch-only. "
        r"Legacy unpaired GKT30 seeds 17/1234 excluded.",
        "",
    ]
    out = ROOT / "results/tables/training_parity.tex"
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {out}")


if __name__ == "__main__":
    raise SystemExit(main())
