"""Generate epoch-matched GKT ablation tables (S21 seed-42; S22 multi-seed) and LaTeX macros."""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd
from scipy import stats

ROOT = Path(__file__).resolve().parents[1]
T3 = float(stats.t.ppf(0.975, df=2))
T9 = float(stats.t.ppf(0.975, df=8))


def _paired_ci(delta: np.ndarray, t_val: float) -> tuple[float, float, float]:
    mean = float(np.mean(delta))
    se = float(np.std(delta, ddof=1) / np.sqrt(len(delta)))
    margin = t_val * se
    return mean, mean - margin, mean + margin


def _load_gkt30_seed42() -> pd.Series:
    q1 = pd.read_csv(ROOT / "results/tables/q1_baseline_fold_results.csv")
    part = q1[(q1["split_base_seed"] == 42) & (q1["model"] == "gkt")]
    part = part[part["experiment_tag"].astype(str).str.startswith("gkt_epochs30")]
    if len(part) != 3:
        raise FileNotFoundError("Need three GKT-30ep folds at split_base_seed=42")
    return part.sort_values("fold").set_index("fold")["auc"]


def _pooled_nine_fold() -> tuple[float, float, float, pd.DataFrame]:
    q1 = pd.read_csv(ROOT / "results/tables/q1_baseline_fold_results.csv")
    gkt = q1[
        (q1["model"] == "gkt") & q1["experiment_tag"].astype(str).str.startswith("gkt_epochs30")
    ][["split_base_seed", "fold", "auc"]]
    sk = q1[
        (q1["model"] == "simplekt") & q1["experiment_tag"].astype(str).str.startswith("trio_matched")
    ][["split_base_seed", "fold", "auc"]]
    merged = gkt.merge(sk, on=["split_base_seed", "fold"], suffixes=("_gkt", "_sk"))
    merged["delta"] = merged["auc_gkt"] - merged["auc_sk"]
    m, lo, hi = _paired_ci(merged["delta"].to_numpy(), T9)
    return m, lo, hi, merged


def main() -> None:
    base = pd.read_csv(ROOT / "results/tables/baseline_fold_results.csv")
    base = base[
        (base["dataset"] == "xes3g5m")
        & (base["graph_construction"] == "train_only")
        & (base["model"].isin(["gkt", "simplekt"]))
    ].sort_values(["model", "fold"])

    simple = base[base["model"] == "simplekt"].set_index("fold")["auc"]
    gkt10 = base[base["model"] == "gkt"].set_index("fold")["auc"]
    gkt30 = _load_gkt30_seed42()

    d10 = (gkt10 - simple).to_numpy()
    d30 = (gkt30 - simple).to_numpy()
    gain = (gkt30 - gkt10).to_numpy()

    m10, lo10, hi10 = _paired_ci(d10, T3)
    m30, lo30, hi30 = _paired_ci(d30, T3)
    mgain, lgain, hgain = _paired_ci(gain, T3)
    mpool, lopool, hipool, pool_df = _pooled_nine_fold()

    out = ROOT / "results/tables"
    out.mkdir(parents=True, exist_ok=True)

    pd.DataFrame(
        [
            {"config": "primary_release", "epochs": 10, "gkt_auc_mean": float(gkt10.mean()), "delta": m10},
            {"config": "epoch_matched_seed42", "epochs": 30, "gkt_auc_mean": float(gkt30.mean()), "delta": m30},
            {"config": "epoch_matched_pooled_9fold", "epochs": 30, "gkt_auc_mean": float(pool_df["auc_gkt"].mean()), "delta": mpool},
        ]
    ).to_csv(out / "gkt_epoch_ablation.csv", index=False)
    pool_df.to_csv(out / "gkt_epoch_ablation_pooled.csv", index=False)

    tex_s21 = [
        "% Auto-generated by scripts/generate_gkt_epoch_ablation.py (Table S21)",
        r"\begin{tabular}{lccrrl}",
        r"\toprule",
        r"\textbf{GKT config} & \textbf{Epochs} & \textbf{Batch} & \textbf{Mean AUC} & "
        r"$\boldsymbol{\Delta}$\textbf{ vs \textit{simpleKT}} & \textbf{95\% CI (3 folds)} \\",
        r"\midrule",
        f"Primary release & 10 & 16 & ${gkt10.mean():.3f}$ & ${m10:+.3f}$ & "
        f"$[{lo10:+.3f}, {hi10:+.3f}]$ \\\\",
        f"Epoch-matched ablation & 30 & 32 & ${gkt30.mean():.3f}$ & ${m30:+.3f}$ & "
        f"$[{lo30:+.3f}, {hi30:+.3f}]$ \\\\",
        f"\\textit{{simpleKT}} reference & 30 & 64 & ${simple.mean():.3f}$ & --- & --- \\\\",
        r"\midrule",
        f"Epoch gain (30ep $-$ 10ep GKT) & & & ${mgain:+.3f}$ & & "
        f"$[{lgain:+.3f}, {hgain:+.3f}]$ \\\\",
        r"\bottomrule",
        r"\end{tabular}",
        "",
    ]
    (out / "gkt_epoch_ablation.tex").write_text("\n".join(tex_s21), encoding="utf-8")

    tex_pool = [
        "% Auto-generated by scripts/generate_gkt_epoch_ablation.py (pooled summary)",
        r"\begin{tabular}{lr}",
        r"\toprule",
        r"\textbf{Statistic} & \textbf{Value} \\",
        r"\midrule",
        r"Pooled $\Delta$AUC (GKT $-$ \textit{simpleKT}) & "
        f"${mpool:+.3f}$ [{lopool:+.3f}, {hipool:+.3f}] (9 folds; paired-$t$) \\\\",
        r"Split base seeds & 17, 42, 1234 (fold-aligned graph rebuild each) \\",
        r"\bottomrule",
        r"\end{tabular}",
        "",
    ]
    (out / "gkt_epoch_ablation_pooled.tex").write_text("\n".join(tex_pool), encoding="utf-8")

    macros = [
        rf"\renewcommand{{\GKTthirtydeltavec}}{{{mpool:+.3f}}}",
        rf"\renewcommand{{\GKTthirtydeltaci}}{{$[{lopool:+.3f}, {hipool:+.3f}]$}}",
        rf"\renewcommand{{\GKTthirtyseedFortydeltaci}}{{$[{lo30:+.3f}, {hi30:+.3f}]$}}",
        rf"\renewcommand{{\GKTepochgain}}{{{mgain:+.3f}}}",
        "",
    ]
    (out / "gkt_epoch_ablation_macros.tex").write_text("\n".join(macros), encoding="utf-8")

    print(f"Seed 42: GKT30 delta {m30:+.4f} [{lo30:+.4f}, {hi30:+.4f}]")
    print(f"Pooled 9-fold delta {mpool:+.4f} [{lopool:+.4f}, {hipool:+.4f}]")
    print(f"Epoch gain (seed 42): {mgain:+.4f}")
    print(f"Wrote {out / 'gkt_epoch_ablation.tex'}")


if __name__ == "__main__":
    main()
