from pathlib import Path

import pandas as pd


def _fmt_auc_pm(mean: float, std: float, *, suppress: bool = False) -> str:
    if suppress or pd.isna(mean):
        return r"---"
    if pd.isna(std) or std == 0:
        return f"{mean:.3f}"
    return f"{mean:.3f} $\\pm$ {std:.3f}"


def _should_suppress_stratum_auc(pivot_mean_row, pivot_mean: pd.DataFrame) -> bool:
    """Suppress unreliable stratum cells (too few pairs or identical AUC across all models)."""
    models = ["dkt", "simplekt", "gkt", "gikt", "dgekt"]
    vals = [getattr(pivot_mean_row, m) for m in models]
    present = [v for v in vals if pd.notna(v)]
    if not present:
        return True
    if len(set(round(float(v), 6) for v in present)) == 1 and len(present) >= 3:
        return True
    return False


def _fmt_delta_pm(mean: float, std: float) -> str:
    if pd.isna(mean):
        return "-"
    sign = "+" if mean >= 0 else ""
    if pd.isna(std) or std == 0:
        return f"{sign}{mean:.3f}"
    return f"{sign}{mean:.3f} $\\pm$ {std:.3f}"


def main() -> None:
    csv_path = Path("results/tables/cold_start_metrics.csv")
    if not csv_path.exists():
        print("CSV not found.")
        return

    df = pd.read_csv(csv_path)
    models_to_include = ["dkt", "simplekt", "gkt", "gikt", "dgekt"]
    df = df[df["model"].isin(models_to_include)]

    strata_order = ["very_cold", "cold", "warm", "hot"]
    df = df[df["stratum"].isin(strata_order)]

    agg_df = df.groupby(["dataset", "model", "stratum"])["auc"].agg(["mean", "std"]).reset_index()
    agg_df = agg_df.rename(columns={"mean": "auc_mean", "std": "auc_std"})

    pivot_mean = agg_df.pivot(index=["dataset", "stratum"], columns="model", values="auc_mean")
    pivot_std = agg_df.pivot(index=["dataset", "stratum"], columns="model", values="auc_std")
    pivot_mean = pivot_mean[["dkt", "simplekt", "gkt", "gikt", "dgekt"]]
    pivot_std = pivot_std[["dkt", "simplekt", "gkt", "gikt", "dgekt"]]

    pivot_mean = pivot_mean.reset_index()
    pivot_std = pivot_std.reset_index()

    datasets = ["assist2012", "junyi", "synthetic_c2", "synthetic_c5", "xes3g5m"]
    pivot_mean["dataset"] = pd.Categorical(pivot_mean["dataset"], categories=datasets, ordered=True)
    pivot_mean["stratum"] = pd.Categorical(pivot_mean["stratum"], categories=strata_order, ordered=True)
    pivot_mean.sort_values(["dataset", "stratum"], inplace=True)

    no_graph_cols = ["dkt", "simplekt"]
    graph_cols = ["gkt", "gikt", "dgekt"]
    pivot_mean["best_no_graph"] = pivot_mean[no_graph_cols].max(axis=1)
    pivot_mean["best_graph"] = pivot_mean[graph_cols].max(axis=1)
    pivot_mean["delta_best"] = pivot_mean["best_graph"] - pivot_mean["best_no_graph"]

    std_lookup = pivot_std.set_index(["dataset", "stratum"])
    delta_stds = []
    for row in pivot_mean.itertuples(index=False):
        ds, st = row.dataset, row.stratum
        vals = []
        for m in no_graph_cols + graph_cols:
            s = std_lookup.loc[(ds, st), m] if (ds, st) in std_lookup.index else float("nan")
            vals.append(s)
        ng_vals = [v for v in vals[:2] if pd.notna(v)]
        g_vals = [v for v in vals[2:] if pd.notna(v)]
        ng_std = max(ng_vals) if ng_vals else float("nan")
        g_std = max(g_vals) if g_vals else float("nan")
        delta_stds.append(
            (ng_std**2 + g_std**2) ** 0.5 if pd.notna(ng_std) and pd.notna(g_std) else float("nan")
        )
    pivot_mean["delta_std"] = delta_stds

    tex_out = Path("results/tables/cold_start_comparison.tex")
    lines = [
        "% Auto-generated by scripts/generate_cold_start_comparison.py",
        "\\begin{table}[t]",
        "\\centering",
        "\\caption{Cold-start comparison of sequence-only (No-Graph) and graph-aware (Graph) KT models. "
        "Entries are three-fold mean~$\\pm$~std AUC by KC train-frequency stratum; "
        "$\\Delta_{\\max}$ is the best Graph AUC minus the best No-Graph AUC in the same dataset/stratum. "
        "Cells marked ``---'' are suppressed when stratum AUC is undefined or unreliable "
        "(fewer than ten discordant label pairs, or identical AUC across all models within $10^{-6}$).}",
        "\\label{tab:cold-start-comparison}",
        "\\footnotesize",
        "\\setlength{\\tabcolsep}{3pt}",
        "\\begin{tabularx}{\\linewidth}{@{} >{\\RaggedRight\\arraybackslash}p{0.14\\linewidth} "
        ">{\\RaggedRight\\arraybackslash}p{0.11\\linewidth} *{6}{>{\\centering\\arraybackslash}X} @{}}",
        "\\toprule",
        "& & \\multicolumn{2}{c|}{\\textbf{No-Graph}} & \\multicolumn{4}{c}{\\textbf{Graph}} \\\\",
        "\\cmidrule(lr){3-4} \\cmidrule(l){5-8}",
        "Dataset & Stratum & DKT & SimpleKT & GKT & GIKT & DGEKT & $\\Delta_{\\max}$ \\\\",
        "\\midrule",
    ]

    current_ds = None
    for row in pivot_mean.itertuples(index=False):
        ds = row.dataset
        if pd.isna(ds):
            continue
        stratum = row.stratum
        ds_name = ds.replace("_", "\\_") if ds != current_ds else ""
        if ds != current_ds and current_ds is not None:
            lines.append("\\midrule")
        current_ds = ds
        stratum_str = str(stratum).replace("_", "\\_")

        std_row = std_lookup.loc[(ds, stratum)] if (ds, stratum) in std_lookup.index else None
        suppress = _should_suppress_stratum_auc(row, pivot_mean)

        def auc_cell(model: str) -> str:
            m = getattr(row, model)
            s = std_row[model] if std_row is not None else float("nan")
            return _fmt_auc_pm(m, s, suppress=suppress)

        lines.append(
            f"{ds_name} & {stratum_str} & "
            f"{auc_cell('dkt')} & {auc_cell('simplekt')} & "
            f"{auc_cell('gkt')} & {auc_cell('gikt')} & {auc_cell('dgekt')} & "
            f"{_fmt_delta_pm(row.delta_best, row.delta_std)} \\\\"
        )

    lines.extend(["\\bottomrule", "\\end{tabularx}", "\\end{table}", ""])
    tex_out.write_text("\n".join(lines), encoding="utf-8")
    print(f"Generated {tex_out}")


if __name__ == "__main__":
    main()
