"""Generate epoch-matched GKT ablation table (Table S21) from primary + Q1 runs."""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd
from scipy import stats

ROOT = Path(__file__).resolve().parents[1]
T_VAL = float(stats.t.ppf(0.975, df=2))


def _paired_ci(delta: np.ndarray) -> tuple[float, float, float]:
    mean = float(np.mean(delta))
    se = float(np.std(delta, ddof=1) / np.sqrt(len(delta)))
    margin = T_VAL * se
    return mean, mean - margin, mean + margin


def _load_gkt30_seed42() -> pd.DataFrame:
    q1 = ROOT / "results/tables/q1_baseline_fold_results.csv"
    if q1.exists():
        df = pd.read_csv(q1)
        part = df[(df["split_base_seed"] == 42) & (df["model"] == "gkt")]
        if len(part) == 3:
            return part.sort_values("fold")
    raise FileNotFoundError("Need three GKT-30ep folds at split_base_seed=42 in q1_baseline_fold_results.csv")


def main() -> None:
    base = pd.read_csv(ROOT / "results/tables/baseline_fold_results.csv")
    base = base[
        (base["dataset"] == "xes3g5m")
        & (base["graph_construction"] == "train_only")
        & (base["model"].isin(["gkt", "simplekt"]))
    ].sort_values(["model", "fold"])

    simple = base[base["model"] == "simplekt"].set_index("fold")["auc"]
    gkt10 = base[base["model"] == "gkt"].set_index("fold")["auc"]
    gkt30 = _load_gkt30_seed42().set_index("fold")["auc"]

    d10 = (gkt10 - simple).to_numpy()
    d30 = (gkt30 - simple).to_numpy()
    gain = (gkt30 - gkt10).to_numpy()

    m10, lo10, hi10 = _paired_ci(d10)
    m30, lo30, hi30 = _paired_ci(d30)
    mgain, lgain, hgain = _paired_ci(gain)

    out = ROOT / "results/tables"
    out.mkdir(parents=True, exist_ok=True)

    rows = [
        {
            "config": "primary_release",
            "epochs": 10,
            "batch": 16,
            "gkt_auc_mean": float(gkt10.mean()),
            "delta_vs_simplekt": m10,
            "ci_lower": lo10,
            "ci_upper": hi10,
        },
        {
            "config": "epoch_matched",
            "epochs": 30,
            "batch": 64,
            "gkt_auc_mean": float(gkt30.mean()),
            "delta_vs_simplekt": m30,
            "ci_lower": lo30,
            "ci_upper": hi30,
        },
    ]
    pd.DataFrame(rows).to_csv(out / "gkt_epoch_ablation.csv", index=False)

    tex = [
        "% Auto-generated by scripts/generate_gkt_epoch_ablation.py",
        r"\begin{tabular}{lccrrl}",
        r"\toprule",
        r"\textbf{GKT config} & \textbf{Epochs} & \textbf{Batch} & \textbf{Mean AUC} & "
        r"$\boldsymbol{\Delta}$\textbf{ vs \textit{simpleKT}} & \textbf{95\% CI (3 folds)} \\",
        r"\midrule",
        f"Primary release & 10 & 16 & ${gkt10.mean():.3f}$ & ${m10:+.3f}$ & "
        f"$[{lo10:+.3f}, {hi10:+.3f}]$ \\\\",
        f"Epoch-matched ablation & 30 & 64 & ${gkt30.mean():.3f}$ & ${m30:+.3f}$ & "
        f"$[{lo30:+.3f}, {hi30:+.3f}]$ \\\\",
        f"\\textit{{simpleKT}} reference & 30 & 64 & ${simple.mean():.3f}$ & --- & --- \\\\",
        r"\midrule",
        f"Epoch gain (30ep $-$ 10ep GKT) & & & ${mgain:+.3f}$ & & "
        f"$[{lgain:+.3f}, {hgain:+.3f}]$ \\\\",
        r"\bottomrule",
        r"\end{tabular}",
        "",
    ]
    (out / "gkt_epoch_ablation.tex").write_text("\n".join(tex), encoding="utf-8")

    macros = [
        rf"\renewcommand{{\GKTthirtydeltavec}}{{{m30:+.3f}}}",
        rf"\renewcommand{{\GKTthirtydeltaci}}{{$[{lo30:+.3f}, {hi30:+.3f}]$}}",
        rf"\renewcommand{{\GKTepochgain}}{{{mgain:+.3f}}}",
        "",
    ]
    (out / "gkt_epoch_ablation_macros.tex").write_text("\n".join(macros), encoding="utf-8")

    print(f"GKT 10ep: mean AUC {gkt10.mean():.4f}, delta {m10:+.4f} [{lo10:+.4f}, {hi10:+.4f}]")
    print(f"GKT 30ep: mean AUC {gkt30.mean():.4f}, delta {m30:+.4f} [{lo30:+.4f}, {hi30:+.4f}]")
    print(f"Epoch gain: {mgain:+.4f} [{lgain:+.4f}, {hgain:+.4f}]")
    print(f"Wrote {out / 'gkt_epoch_ablation.tex'}")


if __name__ == "__main__":
    main()
