"""Paired significance tests and LaTeX CV summary from multi-fold baseline CSVs."""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd
from scipy.stats import ttest_rel, wilcoxon

DATASET_LABELS = {
    "assist2012": r"\makecell[l]{ASSIST\\'12}",
    "xes3g5m": "XES3G5M",
    "junyi": r"\makecell[l]{Junyi\\Academy}",
    "synthetic_c2": "Synthetic C2",
    "synthetic_c5": "Synthetic C5",
}

MODEL_DISPLAY = {
    "simplekt": r"\textit{simpleKT}",
    "gkt": "GKT",
    "gikt": "GIKT",
    "skt": "SKT",
    "dygkt": "DyGKT",
    "dgekt": "DGEKT",
    "akt": "AKT",
    "dkt": "DKT",
    "bkt": "BKT",
}

CV_DATASETS = ["assist2012", "xes3g5m", "junyi"]
# Junyi has no native GKT export; other graph models are present on all folds.
CV_MODELS = {
    "assist2012": ["simplekt", "gkt", "gikt", "skt", "dygkt", "dgekt"],
    "xes3g5m": ["simplekt", "gkt", "gikt", "skt", "dygkt", "dgekt"],
    "junyi": ["simplekt", "gikt", "skt", "dygkt", "dgekt"],
}


def _fmt_pm(mean: float, std: float) -> str:
    if np.isnan(mean):
        return r"--.--- $\pm$ --.---"
    if np.isnan(std) or std == 0.0:
        return rf"{mean:.3f} $\pm$ {std:.3f}"
    return rf"{mean:.3f} $\pm$ {std:.3f}"


def _fmt_p(p: float | None) -> str:
    if p is None or np.isnan(p):
        return "---"
    if p < 0.001:
        return r"$<$0.001"
    return f"{p:.3f}"


def _load_train_only(df: pd.DataFrame) -> pd.DataFrame:
    out = df.copy()
    if "graph_construction" in out.columns:
        out = out[out["graph_construction"].astype(str).str.strip().isin(["train_only", ""])]
    return out


def _summarize_folds(df: pd.DataFrame) -> pd.DataFrame:
    rows: list[dict] = []
    for (dataset, model), part in df.groupby(["dataset", "model"]):
        rows.append(
            {
                "dataset": dataset,
                "model": model,
                "n_folds": int(part["fold"].nunique()),
                "auc_mean": float(part["auc"].mean()),
                "auc_std": float(part["auc"].std(ddof=0)) if len(part) > 1 else 0.0,
                "acc_mean": float(part["acc"].mean()),
                "acc_std": float(part["acc"].std(ddof=0)) if len(part) > 1 else 0.0,
                "nll_mean": float(part["nll"].mean()),
                "nll_std": float(part["nll"].std(ddof=0)) if len(part) > 1 else 0.0,
            }
        )
    return pd.DataFrame(rows)


def run_significance_tests(df: pd.DataFrame, *, min_folds: int = 3) -> pd.DataFrame:
    results: list[dict] = []
    for dataset in df["dataset"].unique():
        ds_pivot = (
            df[df["dataset"] == dataset]
            .pivot_table(index="fold", columns="model", values="auc")
            .dropna(how="any")
        )
        if len(ds_pivot) < min_folds:
            print(f"Skipping {dataset}: needs at least {min_folds} folds (found {len(ds_pivot)}).")
            continue

        base_model = "simplekt" if "simplekt" in ds_pivot.columns else ds_pivot.columns[0]
        base_auc = ds_pivot[base_model]
        print(f"\n--- Dataset: {dataset} (Folds: {len(ds_pivot)}) ---")

        for model in ds_pivot.columns:
            if model == base_model:
                continue
            model_auc = ds_pivot[model]
            _, t_pval = ttest_rel(model_auc, base_auc)
            _, w_pval = wilcoxon(model_auc, base_auc)
            mean_diff = float(model_auc.mean() - base_auc.mean())
            std_diff = float((model_auc - base_auc).std(ddof=0))
            sig_star = "***" if t_pval < 0.01 else ("**" if t_pval < 0.05 else ("*" if t_pval < 0.1 else "ns"))
            print(f"[{model}] vs [{base_model}]:")
            print(f"  Delta Mean AUC: {mean_diff:+.4f} ± {std_diff:.4f}")
            print(f"  Paired t-test p-value : {t_pval:.4f} {sig_star}")
            print(f"  Wilcoxon p-value      : {w_pval:.4f}")
            results.append(
                {
                    "dataset": dataset,
                    "model_a": model,
                    "model_b": base_model,
                    "delta_mean_auc": mean_diff,
                    "std_diff": std_diff,
                    "t_test_pvalue": t_pval,
                    "wilcoxon_pvalue": w_pval,
                    "significance": sig_star,
                }
            )
    return pd.DataFrame(results)


def write_cv_tex(
    fold_df: pd.DataFrame,
    sig_df: pd.DataFrame | None,
    path: Path,
    *,
    placeholder: bool = False,
) -> None:
    summary = _summarize_folds(fold_df) if not fold_df.empty else pd.DataFrame()
    sig_lookup: dict[tuple[str, str], float] = {}
    if sig_df is not None and not sig_df.empty:
        for row in sig_df.itertuples(index=False):
            sig_lookup[(str(row.dataset), str(row.model_a))] = float(row.wilcoxon_pvalue)

    lines = [
        r"% Auto-generated by scripts/significance_testing.py",
        r"\begin{table}[t]",
        r"\centering",
        r"\caption{Three-fold learner CV baseline summary (train-only graphs, valid+test positions). "
        r"Mean~$\pm$~std over folds; $p_{\text{W}}$: Wilcoxon signed-rank test vs.\ \textit{simpleKT} "
        r"(paired fold AUCs).}",
        r"\label{tab:baseline-cv}",
        r"\footnotesize",
        r"\setlength{\tabcolsep}{3pt}",
        r"\begin{tabularx}{\linewidth}{@{} >{\RaggedRight\arraybackslash}p{0.14\linewidth} >{\RaggedRight\arraybackslash}X *{3}{>{\centering\arraybackslash}X} >{\centering\arraybackslash}p{0.08\linewidth} @{}}",
        r"\toprule",
        r"Dataset & Model & AUC & ACC & NLL & $p_{\text{W}}$ \\",
        r"\midrule",
    ]

    for ds_idx, dataset in enumerate(CV_DATASETS):
        models = CV_MODELS[dataset]
        ds_label = DATASET_LABELS.get(dataset, dataset)
        n_models = len(models)
        for m_idx, model in enumerate(models):
            row = summary[(summary["dataset"] == dataset) & (summary["model"] == model)]
            if row.empty or placeholder or (not row.empty and int(row.iloc[0]["n_folds"]) < 3):
                auc_s = acc_s = nll_s = r"--.--- $\pm$ --.---"
                p_s = "---"
            else:
                r0 = row.iloc[0]
                auc_s = _fmt_pm(r0["auc_mean"], r0["auc_std"])
                acc_s = _fmt_pm(r0["acc_mean"], r0["acc_std"])
                nll_s = _fmt_pm(r0["nll_mean"], r0["nll_std"])
                p_s = "---" if model == "simplekt" else _fmt_p(sig_lookup.get((dataset, model)))

            ds_cell = rf"\multirow{{{n_models}}}{{*}}{{{ds_label}}}" if m_idx == 0 else ""
            mname = MODEL_DISPLAY.get(model, model)
            lines.append(rf"{ds_cell} & {mname} & {auc_s} & {acc_s} & {nll_s} & {p_s} \\")
        if ds_idx < len(CV_DATASETS) - 1:
            lines.append(r"\midrule")

    lines.extend([r"\bottomrule", r"\end{tabularx}", r"\end{table}", ""])
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    print("Running significance testing on cross-validation folds...")
    csv_path = Path("results/tables/baseline_fold_results.csv")
    out_dir = Path("results/tables")
    tex_path = out_dir / "baseline_cv_template.tex"

    if not csv_path.exists():
        print("Error: results/tables/baseline_fold_results.csv not found.")
        print("Please ensure you have run the full pipeline with n_folds=3.")
        write_cv_tex(pd.DataFrame(), None, tex_path, placeholder=True)
        print(f"Wrote placeholder CV table to {tex_path}")
        return

    df = _load_train_only(pd.read_csv(csv_path))
    required_cols = {"dataset", "fold", "model", "auc", "acc", "nll"}
    if not required_cols.issubset(df.columns):
        print(f"Error: CSV missing required columns. Found: {df.columns.tolist()}")
        return

    pivot = df.pivot_table(index=["dataset", "fold"], columns="model", values="auc").dropna()
    if pivot.empty:
        print("Error: No complete overlapping folds found to perform paired tests.")
        write_cv_tex(df, None, tex_path, placeholder=True)
        return

    print(f"Found {len(pivot)} fold-dataset pairs for testing.")
    sig_df = run_significance_tests(df)

    if not sig_df.empty:
        sig_path = out_dir / "significance_tests.csv"
        sig_df.to_csv(sig_path, index=False)
        print(f"\nSaved significance test results to {sig_path}")

    has_three_folds = any(
        df[df["dataset"] == ds]["fold"].nunique() >= 3 for ds in CV_DATASETS if ds in set(df["dataset"])
    )
    write_cv_tex(df, sig_df if not sig_df.empty else None, tex_path, placeholder=not has_three_folds)
    print(f"Wrote CV LaTeX table to {tex_path}")


if __name__ == "__main__":
    main()
