"""Summarize Phase 3 trio + cross-tag GKT comparisons from Q1 merged tables."""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd
from scipy import stats

ROOT = Path(__file__).resolve().parents[1]
T_VAL = float(stats.t.ppf(0.975, df=2))


def _paired_ci(delta: np.ndarray) -> tuple[float, float, float]:
    mean = float(np.mean(delta))
    se = float(np.std(delta, ddof=1) / np.sqrt(len(delta)))
    margin = T_VAL * se
    return mean, mean - margin, mean + margin


def _write_trio_tex(rows: list[dict], out: Path) -> None:
    lines = [
        "% Auto-generated by scripts/summarize_q1_phase3.py",
        r"\begin{tabular}{lrrrr}",
        r"\toprule",
        r"\textbf{Seed} & \textbf{Model} & \textbf{Mean AUC} & $\boldsymbol{\Delta}$\textbf{ vs \textit{simpleKT}} & \textbf{95\% CI (3 folds)} \\",
        r"\midrule",
    ]
    for seed in sorted({r["split_base_seed"] for r in rows if r["model"] != "simplekt"}):
        sk = next(r for r in rows if r["split_base_seed"] == seed and r["model"] == "simplekt")
        lines.append(
            f"{seed} & \\textit{{simpleKT}} & ${sk['mean_auc']:.3f}$ & --- & --- \\\\"
        )
        for model in ("gikt", "gkt"):
            hit = [r for r in rows if r["split_base_seed"] == seed and r["model"] == model]
            if not hit:
                continue
            r = hit[0]
            ci = f"$[{r['ci_lower']:+.3f}, {r['ci_upper']:+.3f}]$" if r.get("ci_lower") is not None else "---"
            d = "---" if r.get("delta_vs_simplekt") is None else f"${r['delta_vs_simplekt']:+.3f}$"
            src = r.get("source_tag", "")
            lines.append(
                f"{seed} & {model.upper() if model == 'gikt' else 'GKT'} & ${r['mean_auc']:.3f}$ & {d} & {ci} \\\\"
                f" & \\multicolumn{{4}}{{l}}{{\\footnotesize source: \\texttt{{{src}}}}} \\\\"
            )
        lines.append(r"\midrule")
    if lines[-1] == r"\midrule":
        lines[-1] = r"\bottomrule"
    else:
        lines.append(r"\bottomrule")
    lines += [r"\end{tabular}", ""]
    out.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    merged = ROOT / "results/tables/q1_baseline_fold_results.csv"
    df = pd.read_csv(merged)
    df = df[(df["dataset"] == "xes3g5m") & (df["graph_construction"].fillna("train_only") == "train_only")]

    trio = df[df["experiment_tag"].str.startswith("trio_matched", na=False)]
    gkt_runs = df[df["experiment_tag"].str.startswith("gkt_epochs30", na=False)]

    rows: list[dict] = []
    print("=== Phase 3 primary trio (simpleKT + GIKT retrained; GKT from Phase 1/2) ===\n")

    for seed in sorted(trio["split_base_seed"].unique()):
        seed = int(seed)
        tpart = trio[trio["split_base_seed"] == seed]
        sk = tpart[tpart["model"] == "simplekt"].sort_values("fold")
        sk_mean = float(sk["auc"].mean())
        rows.append(
            {
                "split_base_seed": seed,
                "model": "simplekt",
                "mean_auc": sk_mean,
                "source_tag": tpart["experiment_tag"].iloc[0],
            }
        )
        print(f"Seed {seed} — simpleKT (trio): mean AUC {sk_mean:.4f}")

        gpart = tpart[tpart["model"] == "gikt"].sort_values("fold")
        if len(gpart) == 3:
            mdf = sk[["fold", "auc"]].merge(gpart[["fold", "auc"]], on="fold", suffixes=("_sk", "_g"))
            d = (mdf["auc_g"] - mdf["auc_sk"]).to_numpy()
            m, lo, hi = _paired_ci(d)
            rows.append(
                {
                    "split_base_seed": seed,
                    "model": "gikt",
                    "mean_auc": float(gpart["auc"].mean()),
                    "delta_vs_simplekt": m,
                    "ci_lower": lo,
                    "ci_upper": hi,
                    "source_tag": gpart["experiment_tag"].iloc[0],
                }
            )
            print(
                f"         GIKT (trio):  mean AUC {gpart['auc'].mean():.4f}  "
                f"delta vs simpleKT {m:+.4f} [{lo:+.4f}, {hi:+.4f}]"
            )

        gkt_part = gkt_runs[gkt_runs["split_base_seed"] == seed].sort_values("fold")
        if len(gkt_part) == 3:
            mdf = sk[["fold", "auc"]].merge(gkt_part[["fold", "auc"]], on="fold", suffixes=("_sk", "_gkt"))
            d = (mdf["auc_gkt"] - mdf["auc_sk"]).to_numpy()
            m, lo, hi = _paired_ci(d)
            ok = float(gkt_part["auc"].mean()) > 0.80
            rows.append(
                {
                    "split_base_seed": seed,
                    "model": "gkt",
                    "mean_auc": float(gkt_part["auc"].mean()),
                    "delta_vs_simplekt": m,
                    "ci_lower": lo,
                    "ci_upper": hi,
                    "source_tag": gkt_part["experiment_tag"].iloc[0],
                    "valid": ok,
                }
            )
            flag = "OK" if ok else "SUSPECT — check graph rebuild"
            print(
                f"         GKT  (Phase1/2): mean AUC {gkt_part['auc'].mean():.4f}  "
                f"delta vs simpleKT {m:+.4f} [{lo:+.4f}, {hi:+.4f}]  [{flag}]"
            )
        print()

    out_dir = ROOT / "results/tables"
    out_dir.mkdir(parents=True, exist_ok=True)
    pd.DataFrame(rows).to_csv(out_dir / "q1_phase3_trio_summary.csv", index=False)
    _write_trio_tex(rows, out_dir / "q1_phase3_trio_summary.tex")
    print(f"Wrote {out_dir / 'q1_phase3_trio_summary.csv'}")
    print(f"Wrote {out_dir / 'q1_phase3_trio_summary.tex'}")


if __name__ == "__main__":
    main()
