"""Aggregate assist2012 pyKT folds and refresh reference.txt comparison table."""

from __future__ import annotations

import re
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
CSV = ROOT / "results" / "tables" / "baseline_fold_results.csv"
REF = ROOT / "reference.txt"

MODELS = ("gkt", "dkt", "akt", "simplekt", "bkt", "gikt")
# Paper proxy: pyKT NeurIPS 2022 Table 2 ASSISTments2009 question-level AUC (NOT same dataset).
PAPER_PROXY_AS2009 = {
    "gkt": 0.7424,
    "dkt": 0.7541,
    "akt": 0.7853,
    "simplekt": None,  # not in T2 under that name
    "bkt": None,
    "gikt": None,
}


def _agg() -> pd.DataFrame:
    df = pd.read_csv(CSV)
    sub = df[
        (df["dataset"] == "assist2012")
        & (df["graph_construction"] == "train_only")
        & (df["status"].isin(["pykt_checkpoint", "classical_bkt_em"]))
    ].copy()
    if sub.empty:
        raise SystemExit("No assist2012 pykt rows in baseline_fold_results.csv")
    g = (
        sub.groupby(["model", "status"], as_index=False)
        .agg(auc=("auc", "mean"), acc=("acc", "mean"), n_folds=("fold", "nunique"))
    )
    return g


def _fmt(x: float) -> str:
    return f"{x:.6f}"


def _delta_pct(ncs: float, paper: float | None) -> str:
    if paper is None or paper == 0:
        return "N/A (proxy)"
    return f"{100.0 * (ncs - paper) / paper:+.2f}%"


def _pass_overall(delta: str) -> str:
    if delta.startswith("N/A"):
        return "proxy-only"
    try:
        v = float(delta.rstrip("%").replace("+", ""))
        return "PASS" if abs(v) <= 5.0 else "FAIL"
    except ValueError:
        return "?"


def main() -> None:
    g = _agg()
    lines = [
        "# AUTO-GENERATED by scripts/update_verify_reference.py — do not hand-edit table rows below",
        "",
        "| model | metric | paper_proxy_AS2009 | ncs_mean | delta_pct_vs_proxy | pass_5pct | n_folds | notes |",
        "|-------|--------|-------------------|----------|-------------------|-----------|---------|-------|",
    ]
    for model in MODELS:
        row = g[g["model"] == model]
        if row.empty:
            lines.append(f"| {model} | AUC | — | MISSING | — | — | 0 | not run |")
            continue
        auc = float(row["auc"].iloc[0])
        acc = float(row["acc"].iloc[0])
        nf = int(row["n_folds"].iloc[0])
        proxy = PAPER_PROXY_AS2009.get(model)
        d_auc = _delta_pct(auc, proxy)
        lines.append(
            f"| {model} | AUC | {proxy if proxy else '—'} | {_fmt(auc)} | {d_auc} | "
            f"{_pass_overall(d_auc)} | {nf} | train_only pykt |"
        )
        lines.append(
            f"| {model} | ACC | — | {_fmt(acc)} | — | — | {nf} | |"
        )

    block = "\n".join(lines) + "\n"
    text = REF.read_text(encoding="utf-8")
    marker_start = "# AUTO-GENERATED"
    marker_end = "# END AUTO-GENERATED"
    if marker_start in text and marker_end in text:
        pre = text.split(marker_start)[0]
        post = text.split(marker_end, 1)[1]
        new_text = pre + block + marker_end + post
    else:
        new_text = text.rstrip() + "\n\n" + block + marker_end + "\n"
    REF.write_text(new_text, encoding="utf-8")
    print(block)
    print(f"Updated {REF}")


if __name__ == "__main__":
    main()
